= Rahmengeschäftsordnung der Fachschaften der Heinrich-Heine-Universität Düsseldorf

include::util::disclaimer.adoc[]

[#_1]
== I. Organisationen der Fachschaft und des Fachschaftsrats

[#__1]
=== § 1 Die Fachschaft
Die Fachschaft ist eine rechtlich unselbständige Gliedkörperschaft der Studierendenschaft der Heinrich-Heine-Universität. Die Zugehörigkeit eines oder mehrerer Studiengänge zu einer Fachschaft wird in der Zuordnungsordnung (ZOO) der Studierendenschaft der Heinrich-Heine-Universität Düsseldorf geregelt, außer die Satzung der Studierendenschaft widerspricht dem.

[#__2]
=== § 2 Die Aufgaben der Fachschaft#

Die Fachschaft hat die folgenden Aufgaben (siehe xref:satzung::index.adoc#__45[§ 45 Satzung, „Aufgaben einer Fachschaft“]):

. die Belange ihrer Mitglieder in Studierendenschaft, Universität und Gesellschaft wahrzunehmen,
. die Interessen ihrer Mitglieder, insbesondere die hochschulpolitischen Interessen, zu vertreten,
. die jeweiligen Studierenden der Studiengänge und Studienrichtungen, deren Studierende der Fachschaft zugeordnet sind, in ihrer Gesamtheit zu vertreten,
. an der Erfüllung der Aufgaben der Studierendenschaft und der Universität, insbesondere durch Stellungnahmen zu hochschul- oder wissenschaftspolitischen Fragen, mitzuwirken,
. auf der Grundlage der verfassungsmäßigen Ordnung die politische Bildung, das staatsbürgerliche Verantwortungsbewusstsein und die Bereitschaft zur aktiven Toleranz ihrer Mitglieder zu fördern,
. die fachlichen, wirtschaftlichen, sozialen und kulturellen Belange ihrer Mitglieder wahrzunehmen,
. den Studierendensport innerhalb der Fachschaft und in Kooperation mit anderen Fachschaften zu fördern,
. überörtliche und internationale Studierendenbeziehungen auf Fachebene zu pflegen.

[#__3]
=== § 3 Organe der Fachschaft

Die Organe einer Fachschaft sind nach xref:satzung::index.adoc#__46[§ 46 Satzung, „Organe einer Fachschaft“]:

. Fachschaftsvollversammlung (FSVV)
+
Die FSVV ist die Versammlung aller Mitglieder der Fachschaft.

. Fachschaftsrat
+
Der Fachschaftsrat (im Weiteren FSR) ist das ausführende Organ der Fachschaft.


[#__4]
=== § 4 Die Fachschaftsvollversammlung (FSVV) und ihre Aufgaben

. Die FSVV hat folgende Aufgaben (xref:satzung::index.adoc#__52_2[§ 52 Abs.2 der Satzung, „Aufgaben und Zuständigkeiten der FSVV“]):
+
--
.. den allgemeinen Bericht des FSR einmal im Semester entgegenzunehmen;
.. die studentischen Mitglieder in die Gremien der Universität zu wählen, sofern deren Bestellung der Fachschaft zukommt;
.. über alle Angelegenheiten, die die Fachschaft betreffen, zu diskutieren.
--
+
--
Sofern die Bildung einer FSV für die Fachschaft nicht vorgesehen ist, hat die FSVV zusätzlich folgende Aufgaben:

.. stellvertretend für den FSR zu beschließen;
.. Richtlinien zur Verausgabung der Finanzmittel der Fachschaft zu beschließen;
.. über die Satzung und die Ordnungen der Fachschaft zu beschließen;
.. den Bericht über die Einnahmen und Ausgaben der Fachschaft und den Stand der Fachschaftsmittel einmal im Semester entgegenzunehmen.
--

. Näheres zur FSVV ist in den §§ xref:satzung::index.adoc#__51[51]-xref:satzung::index.adoc#__55[55] Satzung geregelt. Ansonsten gilt diese Rahmengeschäftsordnung entsprechend mit Ausnahme von:

.. <<__15,§ 15, „Ankündigung“>>,
.. <<__17,§ 17, „Tagungsintervall“>>,
.. <<__28,§ 28 Satz 3, „Unterbrechung oder Vertagung der Sitzung“>>,
.. <<__31,§ 31, „Beschlussfähigkeit und Beschlussunfähigkeit“>>,
.. <<__32,§ 32, „Tagesordnung“>>,
.. <<__33,§ 33, „Anträge und Anfragen“>>,
.. <<__36_14,§ 36 Nr. 14, „Die Anträge zur Geschäftsordnung im Einzelnen“>>,
.. <<__38,§ 38, „Gültigkeit eines Beschlusses“>>,
.. <<__43,§ 43, „Umlaufbeschlüsse“>>,
.. <<__56,§ 56, „Wahlen im Sinne dieser Geschäftsordnung“>>,
.. <<__57,§ 57, „Kontaktdaten“>>.
. Anstelle des FSR tritt die FSVV und anstelle der Mitglieder des FSR treten die Mitglieder der FSVV mit Ausnahme von <<__24,§ 24>>, <<__29,§ 29>> und <<__30,§ 30>>.
. Zusätzlich ist zu einem GO-Antrag nach <<__36_7,§ 36 Nr. 7>> die Zustimmung von mindestens einem weiteren Mitglied der FSVV nötig und zur Zurückstellung und Vertagung eines Beschlusses nach <<__36_22,§ 36 Nr. 22>> weiterhin die Mehrheit der anwesenden FSR Mitglieder nötig und ausreichend.

[#__5]
=== § 5 Der Fachschaftsrat und seine Aufgaben

Der Fachschaftsrat hat die folgenden Aufgaben (xref:satzung::index.adoc#__56[§ 56 der Satzung, „Aufgaben und Zuständigkeit des FSR“]):

. die Fachschaft zu vertreten,
. die Aufgaben der Fachschaft wahrzunehmen,
. die Geschäfte der laufenden Verwaltung zu erledigen,
. die Vertretung der Fachschaft auf der FSVK zu bestellen,
. den Haushaltsplan der Fachschaft festzustellen,
. über die weiteren Angelegenheiten der Fachschaft, soweit nicht ein anderes Organ der Fachschaft, Studierendenschaftsorgan oder Gremium zuständig ist, zu beschließen.

[#__6]
=== § 6 Der Fachschaftsrat und seine Aufgaben
Der FSR wird von den Mitgliedern der Fachschaft in allgemeiner, unmittelbarer, freier, gleicher und geheimer Wahl gewählt. Wählbar sind die Mitglieder der Fachschaft, jedes Mitglied der Studierendenschaft darf nur Mitglied in einem Fachschaftsrat sein. Die Wahl geschieht nach den Grundsätzen der Zustimmungswahl. Näheres regelt xref:satzung::index.adoc#__57[§ 57 der Satzung, „Wahl des FSR“], sowie die Wahlordnung der Studierendenschaft.

[#__7]
=== § 7 Offizielle Posten des Fachschaftsrats
. Der Fachschaftsrat hat folgende offizielle Posten und die in Klammern genannten Anzahlen an Hauptverantwortlichen und Stellvertretungen bzw. Verantwortlichen:
.. Sitzungskoordination (je genau eine hauptverantwortliche Person und Stellvertretung)
.. E-Mail-Beauftragte (mindestens zwei Verantwortliche)
.. Finanz-Beauftragte (je genau eine hauptverantwortliche Person und Stellvertretung)
.. FSVK-Vertretende (je genau eine hauptverantwortliche Person und Stellvertretung)
.. Post-Beauftragte (mindestens eine verantwortliche Person)
.. Schlüssel-Beauftragte (mindestens eine verantwortliche Person)
.. Webseiten-Beauftragte (mindestens eine verantwortliche Person)
. Der Fachschaftsrat kann unabhängig hiervon weitere Aufgabenbereiche und damit verbundene inoffizielle Posten einrichten, genauso wie offizielle Arbeitskreise bestimmen. Weiteres wird in <<__12,§ 12, „Arbeitskreise und weitere Posten“>>, geregelt.
. Erst nach der Bestellung der Sitzungskoordination können weitere Posten im Fachschaftsrat besetzt werden.
. Zudem kann der Fachschaftsrat sogenannte Fachschaftsassozierte bestimmen. Weiteres regelt <<__13,§ 13, „Fachschaftsratsassoziierte (FRA)>>“.

[#__8]
=== § 8 Aufgaben der offiziellen Posten

. Sitzungskoordination
+
Die Sitzungskoordination ist verantwortlich für die Koordination des FSR, für die Vorbereitung und Durchführung der Sitzungen, für die Beschlussfassung außerhalb der Sitzungen, sowie die Bekanntmachung und Archivierung der Beschlüsse. Die Sitzungskoordination vertritt den FSR, sofern der FSR nicht etwas Anderes bestimmt (siehe xref:satzung::index.adoc#__60[§ 60 Satzung, „Die Sitzungskoordination des FSR“]). +
Sind die Mitglieder der Sitzungskoordination nicht mehr im Amt oder anderweitig nicht in der Lage, ihren Pflichten nachzukommen, so liegt die Bekanntmachung der FSR Sitzung in der Verantwortung des dienstältesten Mitglieds des FSR. Ist dieses verhindert, lädt das nächst jüngere Mitglied des FSR ein.

. E-Mail-Beauftragte +
Die E-Mail-Beauftragten sind für die Pflege der E-Mail-Accounts des Fachschaftsrates und Berichte bezüglich dieser verantwortlich.

. Finanz-Beauftragte +
Die Finanz-Beauftragten sind für die Koordination und Durchführung von Finanzbeschlüssen verantwortlich. Ebenso obliegt ihnen die Aufstellung von Kassenberichten und Haushaltsplänen, sowie für ein regelmäßiger informeller Bericht zu den Finanzen. Nur FSR-Mitglieder dürfen Finanz-Beauftragte sein (xref:satzung::index.adoc#__84_5[§84 Abs. 5 der Satzung, „Finanzen der Fachschaften“]).

. FSVK-Vertretende +
Die FSVK-Vertretenden sind zur Teilnahme an der FSVK verpflichtet und stimmen auf dieser im Namen der Fachschaft ab. Falls keiner der FSVK-Vertretenden auf einer FSVK anwesend sein kann, kann die Stimme an ein anderes Mitglied der Studierendenschaft abgegeben werden, darüber ist das Fachschaftenreferat spätestens 24 Stunden im Voraus in Textform zu informieren. Sie können in ihrer Stimmabgabe per Beschluss weisungsgebunden werden. Weiteres regelt die Geschäftsordnung der FSVK. Die FSVK-Vertretenden berichten dem FSR von der FSVK (xref:satzung::index.adoc#__69[§ 69 Abs. 2 der Satzung, „Begriffsdefinition und Zusammensetzung der FSVK“]).

. Post-Beauftragte +
Post-Beauftragte überprüfen mindestens einmal pro Woche das physische Postfach der Fachschaft und berichten über etwaige Post auf der nächsten Ratssitzung. Sollten die Post-Beauftragten nicht in der Lage sein, persönlich zu berichten, so ist vor der Sitzung ein Bericht in Textform bei der Sitzungskoordination einzureichen.

. Schlüssel-Beauftragte +
Schlüssel-Beauftragte sind für die Pflege des Schlüsselordners und die Kommunikation mit entsprechenden Stellen der Universität verantwortlich. Diese sind dafür verantwortlich, dass Empfangs- und Rückgabebestätigungen dem Fachschaftenreferat übermittelt werden.

. Webseiten-Beauftragte +
Webseiten-Beauftragte sind dafür verantwortlich, die Protokolle der Sitzungen an den üblichen Stellen zu veröffentlichen (siehe xref:satzung::index.adoc#__62_5[§ 62 Abs. 5 Satzung, „Beschlüsse des FSR“]). Weiterhin sind diese dafür verantwortlich, dass Veranstaltungen der Fachschaft auf der Webseite angekündigt werden, sowie den Inhalt der Website zu pflegen.

[#__9]
=== § 9 Ausscheiden aus den Posten des Fachschaftsrats
Die Übernahme eines Postens oder Aufgabe der Fachschaft endet vorzeitig durch

. Exmatrikulation,
. Rücktritt von dem Posten oder der Aufgabe,
. Rücktritt aus dem Fachschaftsrat,
. Tod,
. Beschluss der Vollversammlung,
. Beschluss des Fachschaftsrates.

Die Person informiert die Sitzungskoordination schriftlich über Exmatrikulation und Rücktritt. Die Sitzungskoordination informiert das autonome Fachschaftenreferat über das Ausscheiden und die Neubesetzung von offiziellen Posten der Fachschaft. Die Beschlüsse der Vollversammlung und des Fachschaftsrats über das Ausscheiden aus einem Posten der Fachschaft benötigen je eine ⅔ Mehrheit der abstimmungsberechtigten anwesenden Personen.

[#__10]
=== § 10 Ausscheiden aus dem Fachschaftsrat
Die Amtszeit eines Mitgliedes des Fachschaftsrates endet vorzeitig durch

. Verlust der Amtsfähigkeit in der Studierendenschaft gemäß xref:satzung::index.adoc#__8[§ 8 Satzung, „Amtsfähigkeit inder Studierendenschaft“],
. Ausscheiden aus der Fachschaft,
. Rücktritt, der der Sitzungskoordination schriftlich mitzuteilen ist.

Die Sitzungskoordination ist über das Ausscheiden und die Gründe dafür mindestens in Textform zu informieren. Die Sitzungskoordination informiert das autonome Fachschaftenreferat über das Ausscheiden eines Mitgliedes des Fachschaftsrats, sowie über die Gründe hierzu. xref:satzung::index.adoc#__42[§ 41 der Wahlordnung, „Ausscheiden von Mitgliedern“], für die Wahlen zu den Organen und Gremien der Studierendenschaft der Heinrich-Heine-Universität Düsseldorf und deren Fachschaften gilt entsprechend.

[#__11]
=== § 11 Stellvertretung und Nachrückverfahren
Falls Verantwortliche für einen Posten ausscheiden, übernimmt automatisch die Stellvertretung die Verantwortung für den Posten. Dabei gelten die gleichen Verantwortlichkeiten und Aufgaben wie für die ursprünglich verantwortliche Person(en). Falls bei offiziellen Posten keine Stellvertretung mehr existiert, übernimmt die Sitzungskoordination diesen kommissarisch bis zur nächsten Sitzung.
Auf der nächsten regulären Sitzung werden vakante Posten/Stellvertretungen neu besetzt.

[#__12]
=== § 12 Arbeitskreise und weitere Posten

. Arbeitskreise +
Zur Erfüllung der Aufgaben des Fachschaftsrates, zur Vorbereitung und Unterstützung seiner Arbeit und für Untersuchungszwecke können durch Mehrheitsbeschluss Arbeitskreise eingesetzt werden. Die Sitzungskoordination gibt die erstmalig benannten Mitglieder und die späteren Änderungen dem Fachschaftsrat bekannt. Diese Rahmengeschäftsordnung gilt entsprechend für Arbeitskreise des FSR, an die Stelle der FSR-Mitglieder treten die Mitglieder des Arbeitskreises.

. Mitglieder der Arbeitskreise +
Der Fachschaftsrat benennt satzungsgemäße Mitglieder der Studierendenschaft als Mitglieder der Arbeitskreise. Benennungen sind nur bei protokollierter Zustimmung des benannten Mitgliedes gültig.

. Vorsitz eines Arbeitskreises +
Jeder Arbeitskreis wählt einen Vorsitz aus seiner Mitte. Bis zur Wahl des Vorsitzes und nach dem Ausscheiden des Vorsitzes aus seinem Amt, nimmt die Sitzungskoordination die Aufgaben wahr. Der Arbeitskreis kann eine weitere Person aus seiner Mitte als stellvertretenden Vorsitz wählen.

. Weitere Posten +
Die Fachschaft kann zusätzliche Posten schaffen, indem sie eine Person direkt für einen Posten bestellt und diese Person mit den entsprechenden Aufgaben und Pflichten betraut. Bei Bedarf kann auch eine Stellvertretung bestellt werden. Die Verantwortlichkeiten für jeden Posten werden klar definiert.

. Jeder Arbeitskreis und Posten bleibt bis zur nächsten konstituierenden Sitzung des FSR, bis zum Rücktritt der bestellten Person(en) oder bis zur Auflösung des Postens oder Arbeitskreises durch die absolute Mehrheit der Mitglieder des FSR bestehen.

[#__13]
=== § 13 Fachschaftsratsassoziierte (FRA)
Für die Assoziierung ist eine einfache Mehrheit des Fachschaftsrats notwendig. Für die Aufhebung der Assoziierung ist eine absolute Mehrheit des FSR notwendig. Assoziiert werden, können alle Mitglieder der Studierendenschaft sowie Zweithörer*innen und Teilzeitstudierende der Heinrich-Heine-Universität Düsseldorf. Zur Assoziierung muss sich die Person auf der FSR-Sitzung vorstellen und sich den Fragen der Ratsmitglieder und der weiteren Anwesenden stellen.

[#_2]
== II. Einberufung von Sitzungen

[#__14]
=== § 14 Konstituierende Sitzung
Die Einberufung zur konstituierenden Sitzung erfolgt unverzüglich nach der Veröffentlichung des Wahlergebnisses durch den Wahlausschuss. Die bisherige Geschäftsordnung ist als Beschlussvorschlag der Einladung beizufügen. Bis zur Bestellung einer Sitzungskoordination leitet die Wahlleitung oder eine von ihr beauftragte Person die Sitzung. Die erste Amtshandlung des FSR ist die Bestellung der Sitzungskoordination. Zuvor können keine anderen Wahlen oder Bestellungen durchgeführt oder Beschlüsse gefasst werden außer der Genehmigung der Tagesordnung und von Protokollen vergangener FSR-Sitzungen.

[#__15]
=== § 15 Ankündigung
Die Einberufung der Sitzungen erfolgt – außer in dringlichen Fällen – spätestens drei Tage vor Sitzungstermin in Form einer öffentlichen Bekanntmachung an den üblichen Stellen. Verantwortlich hierfür ist die Sitzungskoordination.

[#__16]
=== § 16 Sitzungstermin
. Bei der Terminfindung soll ein größtmöglicher Konsens zwischen den Mitgliedern des FSR gefunden werden. Die Sitzungen müssen während der Öffnungszeiten der HHU Düsseldorf zwischen 10 Uhr und 20 Uhr beginnen. In Ausnahmefällen sind auch Anfangszeiten während der Öffnungszeiten der HHU zwischen 8 Uhr und 20:30 Uhr möglich.
. Der FSR beschließt entweder einen regelmäßigen Sitzungstermin oder er beschließt auf jeder Sitzung den nächsten Sitzungstermin. In diesen Fällen muss keine Einladung an die Mitglieder ergehen.
. Über den regulären Sitzungstermin hinaus kann die Sitzungskoordination Sitzungen einberufen, wenn die Wahrnehmung der Aufgaben des FSR es erfordert. Sie ist zur Einberufung verpflichtet, wenn mehr als die Hälfte der Mitglieder dieses verlangen.

[#__17]
=== § 17 Tagungsintervall
Der Fachschaftsrat tagt in der Vorlesungszeit in der Regel wöchentlich, mindestens aber zwei Mal im Monat. In der vorlesungsfreien Zeit in der Regel 2-wöchentlich, mindestens einmal pro Monat.

[#__18]
=== § 18 Sitzungsort
Sitzungen finden im Regelfall auf dem Campusgelände der Heinrich-Heine-Universität statt. Unabhängig davon können Sitzungen hybrid (d.h. vor Ort und zusätzlich online) stattfinden, dabei muss die Möglichkeit einer aktiven Teilnahme durch die satzungsgemäßen Mitglieder der Fachschaft sowie deren Möglichkeiten gehört zu werden, sichergestellt werden.

[#__19]
=== § 19 Bekanntmachung
. Die Bekanntmachung der Einladung zur FSR-Sitzung erfolgt – außer in dringlichen Fällen – mindestens drei Tage vor der Sitzung. Sie beinhaltet mindestens: +
* Sitzungsort,
* Sitzungsbeginn (Datum und Uhrzeit),
* einen Tagesordnungsvorschlag,
* einen Verweis auf die noch nicht genehmigten Protokolle vorheriger FSR-Sitzungen,
* und die eingereichten Anträge in Kopie.

. Der Tagesordnungsvorschlag muss enthalten:
+
--
.. TOP 0: Regularien +
* Feststellung der Ordnungsmäßigkeit der Bekanntmachung
* Feststellung der Beschlussfähigkeit
* Genehmigung der Tagesordnung
* Genehmigung der noch nicht genehmigten Protokolle vorheriger FSR-Sitzungen,

.. TOP 1: Berichte +
* Bericht des Fachschaftsrates
* Berichte der Arbeitskreise des FSR

.. Letzter TOP der Sitzung: Verschiedenes

Die Unterpunkte müssen nicht auf der Einladung angegeben werden. Der TOP Berichte soll möglichst früh behandelt werden. <<__31,§ 31 Nr. 4, „Beschlussfähigkeit und Beschlussunfähigkeit“>>, bleibt davon unberührt.
--

. Bei einem regelmäßigen Sitzungstermin reicht es aus, in der Bekanntmachung die Orte und Zeiten zu nennen, an denen der jeweilige Tagesordnungsvorschlag, das vorläufige Protokoll der vorherigen Sitzung und die eingereichten Anträge eingesehen werden können.

[#__20]
=== § 20 Dringlichkeitssitzung
Im Fall von außerordentlicher Dringlichkeit muss eine Sitzung durch die Sitzungskoordination einberufen werden, wenn dieses über die Hälfte der gewählten Mitglieder des FSR durch ihre Unterschrift der Sitzungskoordination gegenüber fordert. Bei Angelegenheiten, welche eine ⅔ Mehrheit benötigen, müssen sich auch ⅔ der Mitglieder des Fachschaftsrats, bei der Sitzungskoordination für eine Dringlichkeitssitzung aussprechen. Des Weiteren verpflichten sie sich mit ihrer Unterschrift zur Teilnahme an der Dringlichkeitssitzung. Die Sitzung des FSR darf frühestens 24 Stunden und muss spätestens drei Werktage nach Erhalt der Forderung stattfinden. Alle Mitglieder des FSR müssen unverzüglich informiert werden. Im Fall einer dringlichen Einberufung dürfen auf dieser Sitzung keine Änderungen, Erlass oder Aufhebung einer Ordnung sowie keine Wahlen beschlossen oder durchgeführt werden.

[#_3]
== III. Durchführung von Sitzungen

[#__21]
=== § 21 Öffentlichkeit
Die Sitzungen des FSR sind öffentlich.

[#__22]
=== § 22 Pünktlichkeit
Die Sitzungen des FSR sollen pünktlich beginnen. Sie müssen spätestens 30 Minuten nach der in der Einladung angegebenen Uhrzeit beginnen.

[#__23]
=== § 23 Redeleitung
Die Redeleitung wird im Regelfall von der Sitzungskoordination übernommen. Sollte diese nicht anwesend sein, leitet das dienstälteste anwesende FSR Mitglied die offene Wahl einer Redeleitung.

[#__24]
=== § 24 Ausschluss der Öffentlichkeit
Die Öffentlichkeit soll ausgeschlossen werden, wenn Angelegenheiten, deren Veröffentlichung der Studierendenschaft, der Fachschaft oder Dritten erheblichen Schaden zufügen könnte, oder schützenswerte persönliche Belange behandelt werden.
Über den Ausschluss der Öffentlichkeit von einzelnen Tagesordnungspunkten entscheidet die einfache Mehrheit des FSR unter Ausschluss der Öffentlichkeit. Bei Ausschluss der Öffentlichkeit dürfen nur Mitglieder des FSR, des autonomen Fachschaftenreferats oder AStA-Vorstands teilnehmen. Mitglieder des autonomen Fachschaftenreferats und des AStA-Vorstands können auf Beschluss des FSR mit einfacher Mehrheit ausgeschlossen werden. Weiteren Personen darf die Teilnahme per Beschluss erlaubt werden. Die Anwesenden in einem nicht-öffentlichen Teil der Sitzung sind zur Verschwiegenheit verpflichtet. Darauf ist durch die Redeleitung hinzuweisen.

[#__25]
=== § 25 Rederecht
In öffentlichen Sitzungen haben alle Mitglieder der Fachschaft, alle assoziierten Mitglieder des FSR, Mitglieder des Wahlausschuss, sowie alle Mitglieder des AStA Rederecht. Anderen Personen kann durch die Redeleitung, nicht jedoch gegen den Willen der Mehrheit der anwesenden Mitglieder des Fachschaftsrats, ein Rederecht eingeräumt werden. Genauso kann es Personen, die nicht Mitglied des FSR oder des AStA sind, durch eine ⅔ Mehrheit der anwesenden Mitglieder des FSR unter Begründung entzogen werden.

[#__26]
=== § 26 Eröffnung der Aussprache
Die Redeleitung hat über jeden Verhandlungsgegenstand, der auf der Tagesordnung steht, die Aussprache zu eröffnen, wenn sie nicht unzulässig oder an besondere Bedingungen geknüpft ist.

[#__27]
=== § 27 Schluss der Aussprache
Ist die Redeliste erschöpft oder meldet sich niemand zu Wort, so erklärt die Redeleitung die Aussprache für geschlossen.

[#__28]
=== § 28 Unterbrechung oder Vertagung der Sitzung
Wenn während der Sitzung störende Unruhe entsteht, die den Fortgang der Verhandlungen infrage stellt, kann die Redeleitung die Sitzung auf bestimmte Zeit, maximal 15 Minuten, unterbrechen. Kann sich die Redeleitung kein Gehör verschaffen, so verlässt diese ihren Platz; die Sitzung wird dadurch unterbrochen. Sieht die Redeleitung einen ordnungsgemäßen Ablauf der Sitzung nicht mehr gewährleistet, vertagt diese die Sitzung.

[#__29]
=== § 29 Pflicht zur Teilnahme
Jedes Mitglied des FSR ist zur Teilnahme an den Sitzungen verpflichtet. Jedes Mitglied des FSR ist verpflichtet, sich im Verhinderungsfall spätestens bis einen Tag vor der Sitzung – bei Krankheit spätestens bis Sitzungsbeginn – bei der Sitzungskoordination zu entschuldigen. Entschuldigungen durch Dritte sind grundsätzlich nicht statthaft. Unentschuldigtes Fehlen muss im Protokoll kenntlich gemacht werden.

[#__30]
=== § 30 Anwesenheitsliste
. Für jede Sitzung wird eine Anwesenheitsliste im Protokoll geführt, auf der die anwesenden Mitglieder des FSR aufgelistet werden. Anschließend werden alle Nicht-Ratsmitglieder mit Redebeitrag, sowie alle weiteren Personen aufgenommen. Alle anwesenden FSR-Mitglieder müssen mit vollständigem Namen aufgenommen werden, alle weiteren Personen werden im öffentlichen Protokoll mit Vornamen und dem Anfangsbuchstaben des Nachnamens geführt.
. Aus dem Sitzungsprotokoll muss hervorgehen, welche Mitglieder des FSR anwesend, entschuldigt und unentschuldigt sind.
. Sollte das Fachschaftenreferat von einem FSR-Mitglied hinzugezogen werden, dann führt das Fachschaftenreferat in der Regel ein internes Protokoll mit Anwesenheitsliste. Bei dieser werden alle anwesenden Personen mit vollständigen Namen aufgeführt.

[#__31]
=== § 31 Beschlussfähigkeit und Beschlussunfähigkeit
[#__31_1]
. Der FSR ist beschlussfähig, wenn die Sitzung ordnungsgemäß bekanntgegeben wurde und mehr als die Hälfte der Mitglieder des FSR anwesend sind.
..	Feststellung der Beschlussfähigkeit +
Zu Beginn jeder Sitzung ist in TOP 0 Regularien die Beschlussfähigkeit des FSR festzustellen. Im weiteren Verlauf der Sitzung ist das Fortbestehen der Beschlussfähigkeit durch die Protokollführung und die Redeleitung ständig nachzuhalten.
..	Folgen der Beschlussunfähigkeit +
Wird auf einer ordnungsgemäß einberufenen Sitzung Beschlussunfähigkeit festgestellt, kann über die für die Sitzung vorgeschlagenen Beschlüsse im Umlaufverfahren entschieden werden.
[#__31_2]
. Andernfalls kann innerhalb einer Woche, jedoch frühestens 24 Stunden nach dem in der Einladung angekündigten Beginn der als beschlussunfähig festgestellten Sitzung, eine weitere Sitzung des FSR stattfinden. Die Sitzungskoordination oder ihre Stellvertretung legen den Termin nach dem größtmöglichen Konsens im FSR fest. Bei dieser ist dann die Beschlussfähigkeit ab einem Drittel der Ratsmitglieder gegeben, jedoch müssen mindestens zwei Ratsmitglieder anwesend sein. Darauf muss in der Bekanntmachung hingewiesen werden. In diesem Fall gilt nicht die normale Frist zur Bekanntmachung, sofern die Ersatzsitzung unverzüglich angekündigt wird. Für Ersatztermine darf kein zusätzlicher Antrag in die Tagesordnung aufgenommen werden.

[#__32]
=== § 32 Tagesordnung
[#__32_1]
. Annahme der Tagesordnung (TO) +
Zu Beginn jeder Sitzung ist über die in der Einladung vorgeschlagene Tagesordnung abzustimmen. Dies ist unabhängig davon, ob die Sitzung beschlussfähig ist. Dazu können durch Mitglieder des FSR und durch FRA Anträge auf Änderung der vorgeschlagenen Tagesordnung gestellt werden. Mit Annahme der Tagesordnung ist diese festgelegt, für spätere Änderungen siehe <<__36_1,§ 36 Nr. 1, „Die Anträge zur Geschäftsordnung im Einzelnen“>>.
[#__32_2]
. Pflicht zur Ankündigung +
Folgende Anträge können nur in die Tagesordnung aufgenommen werden, wenn sie bereits in der Ankündigung der vorgeschlagenen Tagesordnung enthalten sind:
.. Änderungen, Aufhebung oder Erlass von fachschaftseigenen Ordnungen
.. Aufstellung des Haushalts oder eines Nachtrags zum Haushalt
.. Auflösung des Fachschaftsrats
.. Wahl von offiziellen Posten
.. Abwahl von offiziellen Posten
.. Finanzanträge, es sei denn, eine Mehrheit von zwei Drittel der anwesenden Mitglieder des Fachschaftsrats stimmt der Aufnahme eines Finanzantrages in die Tagesordnung zu.
.. Dauerbeschlüsse
.. Bestellung von Awareness-Beauftragten
.. Absetzung von Awareness-Beauftragten
[#__32_3]
. Nichtöffentlicher Sitzungsteil +
Tagesordnungspunkte, die unter Ausschluss der Öffentlichkeit behandelt werden, sollen an das Ende der Sitzung, hinter den öffentlichen TOP Verschiedenes, gelegt werden.
[#__32_4]
. Anfragen und Anträge von Studierenden +
Anfragen und Anträge von Mitgliedern der verfassten Studierendenschaft, die weder Mitglied des Fachschaftsrates noch FRA sind, müssen am Anfang der Tagesordnung nach den Regularien behandelt werden.
[#__32_5]
. Anträge zur Geschäftsordnung +
Anträge zur Geschäftsordnung sind vorrangig zu behandeln und sind in jedem Fall in das Protokoll aufzunehmen.
[#__32_6]
. Verschiedenes +
Der Tagesordnungspunkt „Verschiedenes“ ist am Ende des öffentlichen Sitzungsteils zu behandeln. Wenn es einen nicht-öffentlichen Sitzungsteil gibt, so hat am Ende der Sitzung ein nicht-öffentlicher TOP „Verschiedenes“ zu behandeln. Nach Eröffnung des TOP „Verschiedenes“ dürfen keine Beschlüsse gefasst werden. Ausgenommen hiervon sind Beschlüsse, die im nicht-öffentlichen Sitzungsteil nach dem öffentlichen TOP „Verschiedenes, aber vor Eröffnung des nicht-öffentlichen TOP „Verschiedenes“ gefasst werden.

[#__33]
=== § 33 Anträge und Anfragen
[#__33_1]
. Fristen +
Anträge und Anfragen sollen in Textform bis zum vierten Tag vor der Sitzung bei der Sitzungskoordination eingereicht werden, Anträge benötigen eine Begründung. Anträge und Anfragen, die bis vier Tage vor der Sitzung des FSR bei der Sitzungskoordination eingereicht worden sind, sind unter Berücksichtigung von <<__32_1,§ 32 Abs. 1, „Tagesordnung“>>, in die Tagesordnung der nächsten Sitzung aufzunehmen. Anträge und Anfragen, die später eingereicht werden, werden auf die darauf folgende Sitzung verschoben.
[#__33_2]
. Antrags- und Anfrageberechtigte +
Berechtigt, Anträge und Anfragen zu stellen, sind jedes Mitglied der Fachschaft im Sinne der Satzung, die Arbeitskreise des FSR sowie FRA.
[#__33_3]
. Änderungsanträge +
Antragsberechtigte können bis zum Beginn der Beschlussfassung eines Antrages Änderungsanträge in Textform bei der Sitzungskoordination einreichen oder auf der Sitzung mündlich stellen. Bei mündlichen Änderungsanträgen kann die Protokollführung eine Abschrift in Textform verlangen.
[#__33_4]
. Anfragen +
Alle Mitglieder der Fachschaft, die Arbeitskreise und FRA sind berechtigt, Anfragen an den Fachschaftsrat, einen Arbeitskreis, und einzelne Mitglieder des Fachschaftsrats oder FRA zu stellen. Anfragen, die das Abstimmungsverhalten betreffen, sind unzulässig. Anfragen müssen schriftlich beantwortet werden. Die Antworten müssen der Sitzungskoordination bis zum Sitzungsbeginn zugeleitet werden. Die Sitzungskoordination verliest die Antworten und leitet sie an das fragende Mitglied der Fachschaft bzw. dem fragenden Arbeitskreis oder die fragende FRA Person weiter. Bei Zweifeln an der Rechtmäßigkeit oder der Zulässigkeit einer Anfrage kann der FSR das Fachschaftenreferat hinzuziehen. In diesem Fall wird die Anfrage in der darauffolgenden Sitzung behandelt. Sie muss allerdings nur beantwortet werden, insofern diese rechtmäßig und zulässig ist.
[#__33_5]
. Der FSR sollte Vorlagen für schriftliche Anträge und Anfragen zur Verfügung stellen oder auf diese hinweisen.

[#__34]
=== § 34 Zeitliche Begrenzung der Sitzung
Nach 22 Uhr oder nach 120 Minuten Sitzungszeit (inklusive Unterbrechungen nach <<__36_7,§ 36 Abs. 7, „Die Anträge zur Geschäftsordnung im Einzelnen“>>) darf kein Tagesordnungspunkt außer Verschiedenes aufgerufen werden, es sei denn, mindestens ⅔ der anwesenden Mitglieder des FSR beschließen eine Fortführung der Sitzung.

[#__35]
=== § 35 Anträge zur Geschäftsordnung (GO)
[#__35_1]
. Zweck +
Der Antrag muss sich auf den zur Beratung stehenden Verhandlungsgegenstand oder auf die Tagesordnung beziehen.
[#__35_2]
. Antragstellung +
Liegt eine Meldung für einen GO-Antrag vor, so erhält die antragstellende Person umgehend, spätestens nach dem aktuellen Redebeitrag, das Wort. Um eine Meldung für einen GO-Antrag deutlich zu machen, hebt das Mitglied gleichzeitig bei de Hände. Berechtigt, einen Antrag zur Geschäftsordnung zu stellen sind grundsätzlich alle Fachschaftsmitglieder und FRA, außer diese Geschäftsordnung regelt etwas anderes.
[#__35_3]
. Behandlung und Beschlussfassung +
Auf einen GO-Antrag kann eine Gegenrede durch ein Mitglied des FSR oder FRA erfolgen. Diese kann auch formal erfolgen. Einer inhaltlichen Gegenrede ist gegenüber der formalen Gegenrede der Vorzug zu geben. Auf die Gegenrede ist keine weitere Wortmeldung zulässig, ausgenommen ist eine inhaltliche Gegenrede, die auf formale Gegenrede folgt.
Erfolgt eine Gegenrede, wird unverzüglich über den GO-Antrag abgestimmt, falls die antragstellende Person diesen nicht zuvor zurückzieht. Erfolgt keine Gegenrede, ist der GO-Antrag angenommen. Wird vor der Abstimmung ein weiterer GO-Antrag gestellt, muss dieser weiterführend sein, um sofort berücksichtigt zu werden. In diesem Fall wird über den weiterführenden GO-Antrag zuerst abgestimmt. Zu GO-Anträgen dürfen Einzelne nicht länger als fünf Minuten sprechen.

[#__36]
=== § 36 Die Anträge zur Geschäftsordnung im Einzelnen
[#__36_1]
. Änderung der Tagesordnung +
Eine Änderung der Tagesordnung bedarf einer einfachen Mehrheit, aber kann nicht mehr nach dem Aufrufen des TOP “Verschiedenes” stattfinden. Antragsberechtigt sind hier Mitglieder des FSR und die FRA.
[#__36_2]
. Schluss der Aussprache oder Beendigung des TOP +
Ein Antrag auf Schluss der Aussprache und sofortige Beschlussfassung oder Beendigung des Tagesordnungspunktes bedarf einer absoluten Mehrheit.
[#__36_3]
. Wiedereintritt in die Aussprache +
Ein Antrag auf Wiedereintritt in die Aussprache bedarf einer ⅔ Mehrheit.
[#__36_4]
. Namentliche Abstimmung +
Ein Antrag auf namentliche Abstimmung gilt unmittelbar als abgelehnt bei Gegenrede und kann nicht auf GO Anträge beantragt werden.
[#__36_5]
. Geheime Abstimmung +
Ein Antrag auf Geheime Abstimmung kann nicht zu GO-Anträgen gestellt werden und ist unmittelbar angenommen, eine Gegenrede ist nicht zulässig. Dieser Antrag kann nur von Mitgliedern des FSR und FRA gestellt werden.
[#__36_6]
. Erneute Prüfung der Beschlussfähigkeit +
Ein Antrag auf erneute Prüfung der Beschlussfähigkeit dürfen alle Mitglieder der Fachschaft nach Annahme der Tagesordnung einmal stellen, erlaubt keine Gegenrede und ist somit unmittelbar angenommen. Eine wiederholte Prüfung auf Beschlussfähigkeit auf Verlangen derselben Person ist erst nach Verlassen oder Betreten des Raums durch andere Personen erneut zulässig.
[#__36_7]
. Unterbrechung der Sitzung +
Ein Verlangen auf Unterbrechung der Sitzung muss die zu unterbrechende Zeit beinhalten. Eine Unterbrechung dauert mindestens zwei Minuten und maximal zehn Minuten.
Antragsberechtigt sind nur Mitglieder des FSR und FRA.
Insgesamt darf die Sitzung pro TOP maximal 20 min und pro Person während der gesamten Sitzung maximal 20 min unterbrochen werden. Die Gesamtzeit der Sitzungsunterbrechungen darf 40 min nicht überschreiten. Dauert die Sitzung länger als 120 min, so ist insgesamt eine Unterbrechung von bis zu einem Drittel der Zeit seit Sitzungsbeginn zulässig. Darüber hinausgehende Unterbrechungen der Sitzung sind nur mit Zustimmung des FSR zulässig.
[#__36_8]
. Beschränkung der Redezeit +
Ein Antrag auf Beschränkung der Redezeit muss die gewünschte Zeit pro Person beinhalten. Die Redezeitbeschränkung darf nicht unter einer Minute liegen und gilt für alle Redeberechtigten gleichermaßen. Die Redeleitung unterliegt dieser Beschränkung aus schließlich für die Sitzungsdurchführung betreffende Redebeiträge nicht.
Die Beschränkung der Redezeit gilt grundsätzlich bis zum Ende des TOP, es sei denn, der FSR beschließt etwas anderes. Zur Aufhebung einer Redezeitbeschränkung ist die absolute Mehrheit der anwesenden FSR-Mitglieder nötig.
Wenn die Einführung oder Absetzung einer Redezeitbeschränkung die gesamte Sitzung über gelten soll, ist eine ⅔ Mehrheit der anwesenden FSR-Mitglieder nötig.
[#__36_9]
. Schluss der Redeliste +
Vor der Abstimmung sind die auf der Redeliste stehenden Personen zu nennen. Nach der Annahme des Antrags dürfen sich alle Personen mit Rederecht erneut auf die Redeliste setzen lassen.
[#__36_10]
. Nichtbefassung eines Antrags +
Ein Antrag auf Nichtbefassung eines Antrags kann pro Antrag pro Person höchstens einmal gestellt werden.
[#__36_11]
. Antrag zur vorübergehenden Aussetzung eines Tagesordnungspunktes
[#__36_12]
. Vertagung eines Punktes der Tagesordnung auf die nächste reguläre FSR-Sitzung +
Der selbe TOP soll nicht mehr als zweimal in Folge vertagt werden.
[#__36_13]
. Gemeinsame Aussprache über gleichartige oder im Sachzusammenhang stehende Verhandlungsgegenstände
[#__36_14]
. Vertagung der Sitzung +
Eine Vertagung der Sitzung bedarf der absoluten Mehrheit der anwesenden Mitglieder des FSR.
Wird eine Sitzung vertagt, so soll sie innerhalb einer Woche weitergeführt werden, jedoch frühestens 24 Stunden nach dem angekündigten Beginn der vertagten Sitzung. Die Sitzungskoordination oder ihre Stellvertretung legen den Termin der Fortsetzungssitzung nach dem größtmöglichen Konsens im FSR fest. Zur Fortsetzungssitzung ist unverzüglich gesondert einzuladen.
[#__36_15]
. Einräumung eines Rederechts für Personen, die nicht Mitglied der verfassten Fachschaft, FRA oder AStA-Mitglieder sind. +
[#__36_16]
. Zulassung von Einzelnen zu einem nicht-öffentlichen Sitzungsteil +
Gilt bei Gegenrede eines Mitglieds des FSR als abgelehnt.
[#__36_17]
. En-Bloc-Abstimmung mehrerer Anträge +
Gilt bei Gegenrede durch Mitglieder des FSR als abgelehnt.
Bei Gegenrede durch Antragstellende oder FRA muss abgestimmt werden.
[#__36_18]
. Tagesordnungspunkt im weiteren Verlauf für die Öffentlichkeit schließen (vgl. <<__24,§ 24, „Ausschluss der Öffentlichkeit“>>) +
Eine Begründung muss im Vorfeld oder auf der Sitzung nicht-öffentlich erfolgen und im nicht-öffentlichen Protokoll protokolliert werden.
[#__36_19]
. Entzug des Rederechts einer Person, die nicht Mitglied des FSR ist, für den aktuellen Tagesordnungspunkt +
Die Annahme bedarf einer ⅔ Mehrheit. Des Weiteren kann das Rederecht nach <<__46,§ 46, „Sach- und Ordnungsrufe“>>, entzogen werden.
[#__36_20]
. Sitzungsverweis einer Person, die aktuell kein Rederecht besitzt +
Die Annahme bedarf einer ⅔ Mehrheit. Des Weiteren kann eine Person auch nach <<__47,§ 47, „Wortentzug“>>, der Sitzung verwiesen werden.
[#__36_21]
. Prüfung der objektiven Klarheit über den Inhalt, die Ordnungsmäßigkeit einer Beschlussfassung oder einer Wahl +
Dieser Antrag kann nur unmittelbar nach einer Abstimmung gestellt werden. Hierbei ist keine Gegenrede möglich. Die Anwesenden prüfen den Beschluss oder die Wahl auf ihre objektive Klarheit und Ordnungsmäßigkeit.
Kann die Prüfung auf der Sitzung nicht zufriedenstellend erfolgen, legt die Sitzungskoordination die Angelegenheit dem autonomen Fachschaftenreferat und ggf. dem AStA Vorstand oder dem Rechtsausschuss vor.
[#__36_22]
. Feststellung der objektiven Unklarheit über den Inhalt, die Nichtordnungsmäßigkeit einer Beschlussfassung oder einer Wahl und sofortige Wiederholung dieser Beschlussfassung oder dieses Wahlganges. +
Dieser Antrag kann nur unmittelbar nach einer Abstimmung von MdFSR gestellt werden. Hierbei ist keine Gegenrede möglich. Über die Zulässigkeit entscheidet die Redeleitung, gegebenenfalls nach Rücksprache mit dem autonomen Fachschaftenreferat oder weiteren Stellen des AStA. Hierzu kann ein Beschluss zurückgestellt und vertagt werden, wenn die Mehrheit der anwesenden FSR-Mitglieder dies als notwendig erachtet. Erklärt die Redeleitung den Antrag für nicht zulässig, kann die antragstellende Person den Rechtsausschuss anrufen. Dieser entscheidet binnen drei Wochen ab Anrufung. Der Beschluss des FSR ist bis zu einer verbindlichen Entscheidung des Rechtsausschusses unwirksam.

[#_4]
== IV. Beschlussfassung

[#__37]
=== § 37 Eröffnung der Beschlussfassung
Die Redeleitung eröffnet nach Abschluss der Aussprache und ggf. Wiederholung der Wortlaute der Anträge die Beschlussfassung.

[#__38]
=== § 38 Gültigkeit eines Beschlusses
Ein Beschluss ist gültig, wenn:

. die Sitzung ordnungsgemäß einberufen wurde,
. die Sitzung beschlussfähig war,
. für den Antrag mehr Ja-Stimmen als Nein-Stimmen abgegeben wurden.
. Abweichend von Nr. 3 ist eine ⅔ Mehrheit des Fachschaftsrates nötig für,
.. den Erlass, die Änderung oder die Aufhebung der Geschäftsordnung des FSR gemäß xref:satzung::index.adoc#__62_7[§ 62 Absatz 7 Nr. 1 Satzung].
.. die Beschlussfassung über eine vorgezogene Neuwahl des FSR gemäß xref:satzung::index.adoc#__59_2[§ 59 Absatz 2 Satzung].
. Abweichend von Nr. 3 ist eine absolute Mehrheit der Mitglieder des Fachschaftsrats bei Aufhebung von Beschlüssen nötig.
. Wenn eine andere Mehrheit als in Nr. 3 nötig ist, muss die Redeleitung vor der Abstimmung darauf aufmerksam machen. Dies ist im Protokoll zu vermerken.

[#__39]
=== § 39 Dauer eines Beschlusses
Finanzbeschlüsse gelten bis zum Ende des folgenden Haushaltsjahres gemäß der xref:satzung::index.adoc#__82_7[Satzung § 82 Absatz 7] und xref:satzung::index.adoc#__84_3[§ 84 Absatz 3]. Andere Beschlüsse gelten grundsätzlich bis zum Ende der Amtszeit. Alternativ kann der Fachschaftsrat Dauerbeschlüsse fassen. Diese verlieren spätestens nach 10 Jahren ihre Gültigkeit. Dauerbeschlüsse sind gesondert aufzubewahren und an den üblichen Veröffentlichungsstellen der Fachschaft mindestens für ihre Dauer bekanntzumachen.

[#__40]
=== § 40 Änderungsantrag
Sind zu einem Antrag Änderungsanträge gestellt worden, so ist über diese vor dem Hauptantrag zu beschließen. Soweit der Fachschaftsrat den Änderungsanträgen zustimmt oder sie von der antragstellenden Person in den Hauptantrag übernommen werden, wird der Hauptantrag in der geänderten Fassung zur Beschlussfassung gestellt. Die antragstellende Person des Hauptantrages hat bis zur endgültigen Beschlussfassung das Recht, auch eine geänderte Fassung ihres Antrags zurückzuziehen. In dem Fall darf eine andere Person diesen aufgreifen.

[#__41]
=== § 41 Konkurrierende Anträge
Liegen konkurrierende Anträge vor, so hat die Redeleitung die Beschlussfassung wie folgt durchzuführen:

. Geht ein Antrag weiter als ein anderer, so ist über den weitergehenden Antrag zuerst zu beschließen. Wird dieser angenommen, so werden weniger weitgehende Anträge nicht mehr behandelt.
. Lässt sich eine Reihenfolge im Sinne von Nr. 1 nicht feststellen, so bestimmt sich die Reihenfolge, in der konkurrierende Anträge zur Beschlussfassung gestellt werden, nach der Reihenfolge der Antragstellung. Lässt sich diese nicht mehr feststellen, entscheidet die Redeleitung.
Sodann ist über jeden der Anträge einzeln abzustimmen. Erreichen dabei mehrere Anträge die erforderliche Mehrheit, so sind in der Schlussabstimmung einander widersprechende Anträge gegeneinander abzustimmen.

[#__42]
=== § 42 Abstimmung
Abstimmungen erfolgen durch geeignetes Anzeigen der Stimme der Stimmberechtigten. Ein geeignetes Anzeigen der Stimme bedeutet der Abstimmungsart entsprechend, für die Redeleitung eindeutig auszählbar, und für jeden Stimmberechtigten durchführbar. Die Auszählung der Stimmen erfolgt durch die Redeleitung. Abstimmungen können wie folgt erfolgen:

. Offene Abstimmung
. Auf Antrag ist eine namentliche Abstimmung (siehe <<__36_4,§ 36 Nr. 4>>) durchzuführen, es sei denn, ein Mitglied des FSR widerspricht. Die abgegebenen Stimmen sind namentlich im Protokoll zu dokumentieren.
. Auf Verlangen eines Mitglieds des FSR ist eine Abstimmung (zum Beispiel bei Personenwahlen) geheim durchzuführen (<<__36_5,§ 36 Nr. 5>>).

[#__43]
=== § 43 Umlaufbeschlüsse
Der Fachschaftsrat kann gemäß den Bestimmungen der Satzung (xref:satzung::index.adoc#__62_4[§ 62 Abs. 4, „Beschlüsse des FSR“]) einzelne Beschlüsse auch außerhalb der Sitzung fassen. Dazu veröffentlicht die Sitzungskoordination die Beschlussvorlage zunächst an den üblichen Stellen, woraufhin, die Ratsmitglieder der Sitzungskoordination in geeigneter Weise ihre Stimme übermitteln. Umlaufbeschlüsse sind im Nachhinein durch die Unterschriften der Abstimmenden zu bestätigen.

[#__44]
=== § 44 Sondervotum
Jedes Mitglied des Fachschaftsrats kann seine vom Mehrheitsbeschluss abweichende Meinung in einem Sondervotum schriftlich artikulieren. Das Sondervotum muss in der Sitzung vorgetragen und begründet werden. Sondervoten müssen der Sitzungskoordination binnen 24 Stunden zugeleitet werden, um ins Protokoll aufgenommen zu werden. Soweit Beschlüsse anderen Stellen zugeleitet oder der Öffentlichkeit zugänglich gemacht werden, sind auch die zu Protokoll genommenen Sondervoten weiterzuleiten oder zu veröffentlichen.

[#__45]
=== § 45 Einspruch
Einspruch gegen einen Beschluss oder eine Wahl ist als Antrag nach <<__36,§ 36>> Nr. <<__36_21,21>> und <<__36_22,22>> dieser GO möglich. Über die Zulässigkeit dieses Antrags entscheidet die Redeleitung. Die Beanstandung eines Beschlusses oder einer Wahl kann auch gegenüber dem Rechtsausschuss erklärt werden. Wenn ein Verstoß gegen die Satzung der Studierendenschaft oder andere rechtliche Regelungen vorlag, hat die Sitzungskoordination den entsprechenden Beschluss beim AStA-Vorstand zu beanstanden.

[#_5]
== V. Ordnungsmaßnahmen

[#__46]
=== § 46 Sach- und Ordnungsrufe (SO-Rufe)
. Die Redeleitung kann Redende, die vom Verhandlungsgegenstand abschweifen, zur Sache verweisen.
. Anwesende können von der Redeleitung zur Ordnung gerufen werden, wenn sie die Ordnung oder Würde der Sitzung verletzen. Die Unterbrechung einer persönlichen Erklärung und übermäßiger Alkoholkonsum sind mit einem Ordnungsruf zu ahnden.
. Sämtliche Anwesende haben während der Sitzungen dafür Sorge zu tragen, dass ihre Geräte auf lautlos geschaltet sind. Verstöße gegen diese Regelung haben einen Ordnungsruf zur Folge.
. Gegen einen SO-Ruf kann durch ein Viertel der anwesenden stimmberechtigten Mitglieder des FSR begründet Einspruch bei der Redeleitung eingelegt werden. Über den Einspruch entscheidet der Fachschaftsrat ohne Aussprache in der gleichen Sitzung mit der Mehrheit aller seiner Mitglieder.

[#__47]
=== § 47 Wortentzug
. Nachdem eine Person mindestens zweimal zur Sache oder zur Ordnung gerufen worden ist und mindestens einmal auf die Folgen eines weiteren SO-Rufes hingewiesen wurde, so muss ihr die Redeleitung bei einem weiteren SO-Ruf das Wort entziehen und darf es ihr im laufenden TOP nicht wieder erteilen.
. Personen, die nicht dem Fachschaftsrat oder AStA angehören, kann das Wort für die laufende Sitzung entzogen werden. Bei Widerspruch eines MdFSR entscheidet der Fachschaftsrat sofort mit einfacher Mehrheit über den Widerspruch.

[#__48]
=== § 48 Sitzungsverweis
. Schweift eine Person weiter von der Sache ab oder verletzt weiter die Ordnung oder Würde, nachdem ihr das Wort bereits einmal entzogen wurde, so kann die Redeleitung diese mit Zustimmung des Fachschaftsrats der Sitzung verweisen. Auf einen mit Zwei-Drittel-Mehrheit der Abstimmenden angenommenen Antrag eines MdFSR hin muss sie dies tun.
. Bei gröblicher Verletzung der Ordnung oder der Würde des Fachschaftsrats kann die Redeleitung Personen, die nicht dem Rat angehören, auch ohne, dass ein Ordnungsruf ergangen ist, mit Zustimmung des Rats, des Raumes verweisen. Ist eine Abstimmung unter Anwesenheit der betroffenen Person nicht möglich, so ist diese für die Dauer der Abstimmung des Sitzungsraumes zu verweisen.

[#__49]
=== § 49 Unterbrechung oder Vertagung bei Unruhen
. Wenn während der Sitzung störende Unruhe entsteht, die den Fortgang der Verhandlungen in Frage stellt, kann die Redeleitung die Sitzung auf bestimmte Zeit unterbrechen. Kann sich die Redeleitung kein Gehör verschaffen, so verlässt sie den Platz; die Sitzung wird dadurch unterbrochen.
. Sieht die Redeleitung einen ordnungsgemäßen Ablauf der Sitzung nicht mehr gewährleistet, vertagt sie die Sitzung. <<__36_14,§ 36 Nr. 14>> Sätze 2, 3 und 4 gelten entsprechend.

[#_6]
== VI. Protokoll

[#__50]
=== § 50 Protokoll
. Der Fachschaftsrat bestellt eine oder mehrere Personen als Protokollführung. Die Protokollführung fertigt ein Protokoll der Sitzung an. Besteht die Protokollführung aus mehreren Personen, so muss eine verantwortliche protokollierende Person bestimmt werden.
. Das Protokoll muss möglichst geschlechtsneutral bzw. sensibel und barrierearm formuliert werden. Das Protokoll wird auf Deutsch oder zusätzlich auf Englisch verfasst.

[#__51]
=== § 51 Inhalt des Protokolls
Das Protokoll muss enthalten:

. die Namen der protokollierenden Personen,
. Art der Sitzung,
. Datum und Uhrzeit des Beginns und des Endes der Sitzung,
. eine Anwesenheitsliste, in der aufgelistet sind:
.. alle anwesenden Mitglieder des FSR,
.. alle abwesenden Mitglieder des FSR unterteilt in entschuldigt und unentschuldigt,
.. alle anwesenden Mitglieder des AStA,
.. in jedem Fall alle Personen mit Redebeitrag,
.. weitere anwesende Personen, wenn sie möchten.
.. Näheres regelt <<__30,§ 30, „Anwesenheitsliste“>>,
. die beschlossene Tagesordnung,
. die Anträge im Wortlaut,
. die Beschlüsse im Wortlaut und die Ergebnisse der Abstimmungen,
. auf Antrag die vom Mehrheitsbeschluss abweichende Meinung eines Mitgliedes des FSR (Sondervotum) nach <<__44,§ 44, „Sondervotum“>>, dieser GO,
. die Unterschrift der verantwortlichen protokollierenden Person und der Redeleitung.
. In digital veröffentlichten Versionen des Protokolls kann auf Unterschriften verzichtet werden.

[#__52]
=== § 52 Veröffentlichung des Protokolls
. Das genehmigte Protokoll wird öffentlich an den üblichen Stellen bekannt gemacht. Der FSR archiviert die unterzeichnete Ausfertigung des Protokolls. Waren Teile der Sitzung nicht-öffentlich, so sind die Protokollteile darüber nur den Mitgliedern des FSR und seiner Ausschüsse sowie dem AStA und seinen Beschäftigten zugänglich.
. Das vorläufige Protokoll ist zeitnah – spätestens drei Tage nach der Sitzung – zu veröffentlichen.
. Sämtliche Protokolle müssen möglichst barrierearm veröffentlicht werden.

[#__53]
=== § 53 Genehmigung des Protokolls
[#__53_1]
. Die noch nicht genehmigten Protokolle sind als Verweis der Sitzungseinladung beizufügen. Bis zur Genehmigung des Protokoll zu Beginn der nächsten beschlussfähigen FSR Sitzung können Änderungsanträge zum Protokoll gestellt werden. Diese können von der Protokollführung übernommen werden. Andernfalls stimmt der FSR bei ebenjener beschlussfähigen FSR Sitzung über die Änderungsanträge ab. Anschließend beschließt der FSR die Genehmigung des Protokolls.
[#__53_2]
. Wurde das noch nicht genehmigte Protokoll einer vergangenen Sitzung weniger als drei Tage vor der Sitzung veröffentlicht, so ist die Genehmigung auf Verlangen eines Fachschaftsmitglieds, FRA, Mitglieds des AStA-Vorstands, Anti-FARaDis oder eines autonomen Referatsmitglieds zu vertagen.

[#__54]
=== § 54 Beschlussausfertigung
Beschlüsse des Fachschaftsrats werden von der Sitzungskoordination ausgefertigt und schnellstmöglich, jedoch spätestens sieben Tage nach der Sitzung öffentlich bekannt gemacht.

[#__55]
=== § 55 Aktenführung
Geschäfts- und Schriftführung des Fachschaftsrats sind so zu gestalten, dass beim Amtswechsel sämtliche Geschäftsvorgänge der letzten zehn Jahre aus den Akten eindeutig zu rekonstruieren sind. Mitglieder des Fachschaftsrats haben das Recht, die Akten jederzeit einzusehen. Personenbezogene Daten, die nicht-öffentlich einsehbar waren, sind nach 10 Jahren zu löschen.

[#_7]
== VII. Sonstige Bestimmungen

[#__56]
=== § 56 Wahlen im Sinne dieser Geschäftsordnung
Wenn in dieser Geschäftsordnung von Wahlen die Rede ist, sind offene oder geheime Wahlen möglich, es sei denn, die genaue Art der Wahl ist im jeweiligen Paragraphen festgelegt.

[#__57]
=== § 57 Kontaktdaten
In der konstituierenden Sitzung muss die persönliche HHU-E-Mail-Adresse der gewählten Mitglieder des FSR im Konstituierungsprotokoll festgehalten werden. Der FSR, das autonome Fachschaftenreferat, das Finanzreferat, das IT Referat und die Buchhaltung des AStA erhalten Zugriff auf diese. Die Kontaktdaten müssen laufend aktualisiert werden. Die Mitglieder des FSR sind verpflichtet, die Sitzungskoordination und das autonome Fachschaftenreferat über Veränderungen unverzüglich zu unterrichten. Die Verarbeitung der Kontakt und weiterer personenbezogenen Daten wird im Konstituierungsprotokoll geregelt.

[#__58]
=== § 58 Veröffentlichungen
. Die Veröffentlichung an den üblichen Stellen meint die Veröffentlichung auf der Website. Sollte diese nicht funktionieren, dienen Glaskästen, Tür oder andere Aushangflächen der Fachschaft als Ausweichstelle.
. Sämtliche Veröffentlichungen müssen möglichst barrierearm gestaltet werden.
. Sämtliche Veröffentlichungen müssen möglichst geschlechtsneutral bzw. sensibel gestaltet werden.
. Sämtliche rechtlich relevanten Veröffentlichungen müssen mindestens auf Deutsch verfasst werden. Zudem sollen diese Veröffentlichungen in der Sprache der vertretenen Studiengänge verfasst werden.

[#__59]
=== § 59 Auslegung
Ist in einer Sitzung strittig, wie eine Bestimmung dieser Geschäftsordnung auszulegen ist, oder ist das Verfahren strittig, so entscheidet der FSR mit Mehrheit der anwesenden Mitglieder über den Fortgang der Verhandlung. Bei Gleichheit der Stimmen entscheidet die Redeleitung. Kann der Konflikt auf der Sitzung nicht zufriedenstellend gelöst werden, legt die Sitzungskoordination die Angelegenheit dem autonomen Fachschaftenreferat und ggf. dem AStA Vorstand oder dem Rechtsausschuss vor.

[#_8]
== VIII. Schlussbestimmung

[#__60]
=== § 60 Inkrafttreten
Die Rahmengeschäftsordnung tritt nach Beschluss der Fachschaftsvertretendenkonferenz (FSVK) mit Bekanntmachung gemäß xref:satzung::index.adoc#__9_3[§ 9 Absatz 3 Satzung, „Ausfertigung und In-Kraft-Treten von Satzungen und Ordnungen“] in Kraft. Dies gilt auch für Änderungen.

[#_9]
== IX. Anhang
Fachschaftsratsassoziierte (FRA)

* Für die Assoziierung ist eine einfache Mehrheit des Fachschaftsrats notwendig. Für die Aufhebung der Assoziierung ist eine absolute Mehrheit des FSR notwendig. Assoziiert werden können alle Mitglieder der Studierendenschaft sowie Zweithörer*innen und Teilzeitstudierende der Heinrich-Heine-Universität Düsseldorf. Zur Assoziierung muss sich die Person auf der FSR-Sitzung vorstellen und sich den Fragen der Ratsmitglieder und der weiteren Anwesenden stellen. (<<__13,§ 13>>)
* FRA haben Rederecht auf Sitzungen (<<__25,§ 25>>).
* FRA können Anträge auf Änderung der vorgeschlagenen Tagesordnung stellen (<<__32,§ 32>>).
* FRA können Anträge und Anfragen stellen. (<<__33_2,§ 33 Abs. 2>>)
* FRA können angefragt werden. (<<__33_4,§ 33 Abs. 4>>)
* FRA können GO Anträge stellen außer <<__36_22,§ 36 Nr. 22>>
* FRA können Gegenrede gegen GO Anträge erheben (<<__35_3,§ 35 Abs. 3>>), bei Gegenrede gegen En-Bloc-Abstimmung muss dann darüber abgestimmt werden anders als bei FSR Mitgliedern, (<<__36_17,§ 36 Nr. 17>>)
* Wurde das noch nicht genehmigte Protokoll einer vergangenen Sitzung weniger als drei Tage vor der Sitzung veröffentlicht, so ist die Genehmigung auf Verlangen eines [...] FRA zu vertagen. (<<__53_2,§ 53 Abs. 2>>)



